WebUI/Controllers/AdminHomeController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace WebUI.Controllers
{
    public class AdminHomeController : Controller
    {
        // GET: AdminHomeController
        public ActionResult Index()
        {
            return View();
        }

        
    }
}

WebUI/Controllers/CustomerStoreController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using BL;
using WebUI.Models;
using Models;
using System.Diagnostics;

namespace WebUI.Controllers
{
    public class CustomerStoreController : Controller
    {
        private IBL _bl;
        private List<InventoryVM> inventory;
        public CustomerStoreController(IBL bl)
        {
            _bl = bl;
        }
        // GET: CustomerStoreController
        public ActionResult Index()
        {
            List<StoreVM> allStore = _bl.GetAllStore().Select(r => new StoreVM(r)).ToList();
            return View(allStore);
        }

        
        public ActionResult ShoppingCart()
        {
            string olddata = Request.Cookies["LineItem"];
            inventory = _bl.GetOneStoreById(Int32.Parse(Request.Cookies["StoreId"])).Inventory.Select(r => new InventoryVM(r)).ToList();
            List<string> tempData = new List<string>();
            List<LineItemVM> currentLineItem = new List<LineItemVM>();
            LineItemVM l = new LineItemVM();
            Dictionary<string, string> tempData2 = new Dictionary<string, string>();
            if (olddata != null && olddata!="")
            {
                tempData = olddata.Trim().Split(" ").ToList();
                foreach (string s in tempData)
                {
                    List<string> temp = s.Split("-").ToList();
                    l.Name = inventory[Int32.Parse(temp[0])].Name;
                    l.Price = inventory[Int32.Parse(temp[0])].Price;
                    l.Quantity = Int32.Parse(temp[1]);
                    currentLineItem.Add(l);
                }
            }
            else
            {
                ViewBag.message = "Nothing is your shopping cart";
            }
                return View(currentLineItem);
        }
        public ActionResult Inventory(int id)
        {
            
            if (Request.Cookies["StoreId"] != null&&id!=0)
            {
                Response.Cookies.Delete("LineItem");
                Response.Cookies.Delete("StoreId");
                Response.Cookies.Append("StoreId", id + "");
            }else if (id == 0)
            {
                
                inventory = _bl.GetOneStoreById(Int32.Parse(Request.Cookies["StoreId"])).Inventory.Select(r => new InventoryVM(r)).ToList();
                return View(inventory);
            }
            else
            {
                Response.Cookies.Append("StoreId", id + "");
            }
            inventory = _bl.GetOneStoreById(id).Inventory.Select(r=>new InventoryVM(r)).ToList();

            return View(inventory);
        }

        [HttpPost]
        public ActionResult ShoppingCart(int id)
        {

/*            Debug.WriteLine(Request.Cookies["StoreId"]);
            Debug.WriteLine(Request.Form["ItemId"]);
            Debug.WriteLine(Request.Form["ItemQuantity"]);*/
            List<LineItemVM> currentLineItem = new List<LineItemVM>();
            inventory = _bl.GetOneStoreById(Int32.Parse(Request.Cookies["StoreId"])).Inventory.Select(r => new InventoryVM(r)).ToList();
            string olddata = "";
            string dataAsString = "";
            LineItemVM l = new LineItemVM();
            List<string> tempData = new List<string>();
            bool isCurrentItem = false;
            bool isOk = true;
            Dictionary<string, string> tempData2 = new Dictionary<string, string>();
            try
            {
                if (Request.Form["ItemId"] != "" && Request.Form["ItemQuantity"] != "")
                {
                    if (inventory != null)
                    {
                        if (Int32.Parse(Request.Form["ItemId"]) >= 0 && Int32.Parse(Request.Form["ItemId"]) < inventory.Count)
                        {
                            if (Int32.Parse(Request.Form["ItemQuantity"]) >= 0 && Int32.Parse(Request.Form["ItemQuantity"]) < inventory[(Int32.Parse(Request.Form["ItemId"]))].Quantity)
                            {
                                
                                if (Request.Cookies["LineItem"] != null)
                                {
                                    olddata = Request.Cookies["LineItem"];
                                    tempData = olddata.Trim().Split(" ").ToList();
                                    foreach (string s in tempData)
                                    {
                                        List<string> temp = s.Split("-").ToList();
                                        if (temp[0].Equals(Request.Form["ItemId"]))
                                        {
                                            if (Int32.Parse(temp[1]) + Int32.Parse(Request.Form["ItemQuantity"]) <= inventory[(Int32.Parse(Request.Form["ItemId"]))].Quantity)
                                            {
                                                temp[1] = (Int32.Parse(temp[1]) + Int32.Parse(Request.Form["ItemQuantity"])).ToString();
                                                isCurrentItem = true;
                                                tempData2.Add(temp[0], temp[1]);
                                            }
                                            else
                                            {
                                                ViewBag.message = "Value out of range";
                                                isOk = false;
                                            }
                                        }
                                        else
                                        {
                                            tempData2.Add(temp[0], temp[1]);
                                        }

                                    }
                                    if (isCurrentItem == false && isOk)
                                    {
                                        tempData2.Add(Request.Form["ItemId"], Request.Form["ItemQuantity"]);
                                        Response.Cookies.Delete("LineItem");
                                        
                                    }
                                    foreach (KeyValuePair<string, string> kv in tempData2)
                                    {
                                        l = new LineItemVM();
                                        
                                        dataAsString = dataAsString + (kv.Key + "-" + kv.Value + " ");
                                        l.Id = inventory[Int32.Parse(kv.Key)].Id;
                                        l.Name = inventory[Int32.Parse(kv.Key)].Name;
                                        l.Price = inventory[Int32.Parse(kv.Key)].Price;
                                        l.Quantity = Int32.Parse(kv.Value);
                                        currentLineItem.Add(l);
                                    }

                                    Response.Cookies.Append("LineItem", dataAsString);
                                    ViewBag.message = "Adding Successful";
                                    return View(currentLineItem);
                                }
                                else
                                {
                                    
                                    tempData2.Add(Request.Form["ItemId"], Request.Form["ItemQuantity"]);
                                    Response.Cookies.Append("LineItem", dataAsString);
                                    foreach (KeyValuePair<string, string> kv in tempData2)
                                    {
                                        dataAsString = dataAsString + (kv.Key + "-" + kv.Value + " ");
                                        l.Id = inventory[Int32.Parse(kv.Key)].Id;
                                        l.Name = inventory[Int32.Parse(kv.Key)].Name;
                                        l.Price = inventory[Int32.Parse(kv.Key)].Price;
                                        l.Quantity = Int32.Parse(kv.Value);
                                        currentLineItem.Add(l);
                                    }

                                    Response.Cookies.Append("LineItem", dataAsString);
                                    ViewBag.message = "Adding Successful";
                                    return View(currentLineItem);
                                }

                                

                            }
                            else
                            {
                                ViewBag.message = "Quantity out of range";
                            }
                        }
                        else
                        {
                            ViewBag.message = "Id out of range";
                        }
                    }
                    else
                    {
                        ViewBag.message = "There is not inventory for this store";
                    }
                    
                }
                else
                {
                    ViewBag.message = "Value can't be null";
                }
            }
            catch
            {
                ViewBag.message = "Value need to be number";
            }
            return View(currentLineItem);

        }


        public ActionResult PlaceOrder()
        {
            List<LineItem> currentLineItem = new List<LineItem>();
            inventory = _bl.GetOneStoreById(Int32.Parse(Request.Cookies["StoreId"])).Inventory.Select(r => new InventoryVM(r)).ToList();
            string dataString = "";
            LineItemVM l = new LineItemVM();
            
            List<string> tempData = new List<string>();
            List<string> temp = new List<string>();
            Dictionary<string, string> tempData2 = new Dictionary<string, string>();
            OrderVM newOrder = new OrderVM();

WebUI/Controllers/StoreController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Models;
using BL;
using WebUI.Models;

namespace WebUI.Controllers
{
    public class StoreController : Controller
    {
        // GET: StoreController
        private IBL _bl;
        public StoreController(IBL bl)
        {
            _bl = bl;
        }
        public ActionResult Index()
        {
            List<StoreVM> allStore = _bl.GetAllStore().Select(r => new StoreVM(r)).ToList();
            return View(allStore);
        }

        // GET: StoreController/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: StoreController/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: StoreController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(StoreVM storeVM)
        {
            try
            {
                //if the data in my form is valid
                if (ModelState.IsValid)
                {
                    _bl.Add(storeVM.ToModel());
                    return RedirectToAction(nameof(Index));
                }
                return View();
            }
            catch (Exception e)
            {
                return View();
            }
        }

        public ActionResult Inventory(int id)
        {
            List<InventoryVM>inventory = _bl.GetOneStoreById(id).Inventory.Select(r => new InventoryVM(r)).ToList();
            return View(inventory);
        }

        // GET: StoreController/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: StoreController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: StoreController/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: StoreController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

WebUI/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] -Liquor Store</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Liquor Store</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Store" asp-action="Index">Stores</a>
                        </li>
                    </ul>

                    <ul class="nav navbar-nav navbar-right">
                        <li><a asp-area="" class="button-secondary pure-button" asp-controller="CustomerHome" asp-action="Create" >Sign Up  </a></li>
                        <li><a asp-area="" class="button-secondary pure-button" asp-controller="CustomerHome" asp-action="login" >  Login</a></li>

                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - WebUI - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>
<style>
    .button-secondary {
        color: white;
        border-radius: 4px;
        text-shadow: 0 1px 1px rgba(0, 0, 0, 0.2);
        margin: 0px 3px;
        padding: 3px;
        background: rgb(66, 184, 221);
    }

</style>

WebUI/Views/Shared/_LayoutAdmin.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] -Liquor Store</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="AdminHome" asp-action="Index">Liquor Store</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="AdminCustomer" asp-action="Index">Customer</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="AdminStore" asp-action="Index">Stores</a>
                        </li>
                    </ul>

                    <ul class="nav navbar-nav navbar-right">
                        <li><a asp-area="" class="button-secondary pure-button" asp-controller="CustomerHome" asp-action="Logout"> Logout </a></li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - WebUI - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>
<style>
    .button-secondary {
        color: white;
        border-radius: 4px;
        text-shadow: 0 1px 1px rgba(0, 0, 0, 0.2);
        margin: 0px 3px;
        padding: 3px;
        background: rgb(28, 184, 65);
    }
</style>

WebUI/Views/Shared/_LayoutCustomer.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] -Liquor Store</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="CustomerHome" asp-action="Index">Liquor Store</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="CustomerHome" asp-action="Index">Profile</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="CustomerStore" asp-action="Index">Stores</a>
                        </li>
                    </ul>

                    <ul class="nav navbar-nav navbar-right">
                        <li><a asp-area="" class="button-secondary pure-button" asp-controller="CustomerHome" asp-action="Logout" > Logout </a></li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - WebUI - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>
<style>
    .button-secondary {
        color: white;
        border-radius: 4px;
        text-shadow: 0 1px 1px rgba(0, 0, 0, 0.2);
        margin: 0px 3px;
        padding: 3px;
        background: rgb(28, 184, 65);
    }
</style>